image: maven:3.6.2-jdk-11

variables:
  # configure Maven to:
  #   - use a cache directory inside the build directory so it works with Gitlab caching
  #   - print the datetime with each command so it's easier to slow steps in the CI
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss"
  # configure Yarn to:
  #   - use a cache directory inside the build directory so it works with Gitlab caching
  #   - throw an error if there is a difference between the yarn.lock on CI and in the repo
  YARN_INSTALL_ARGS: "install --cache-folder .yarn --pure-lockfile"

cache:
  # This cache key is shared across projects and determines the cache that is loaded before the job starts
  # if your dependencies (Java or Javascript) change then the version should be changed in order to keep
  # CI builds running quickly
  key: v6
  paths:
    # Maven dependencies
    - .m2/repository/
    # Yarn dependencies - using node_modules/ does not work well with Gitlab
    - powo-dashboard/.yarn/
    # NPM dependencies - using node_modules/ does not work well with Gitlab
    - powo-portal/src/main/frontend/.yarn/

build_and_test:
  stage: test
  script:
    - mvn test
