version: '2'
services:
  db:
    image: eu.gcr.io/powop-1349/db:latest
    env_file:
      - src/main/resources/docker/env/common.env
      - src/main/resources/docker/env/portal.env
    volumes:
      - portal_data:/var/lib/mysql
#      - /tmp/powo-uat-2018-06-04.sql.gz:/docker-entrypoint-initdb.d/00-powo.sql.gz # uncomment and point to powo dump to load existing database
    ports:
      - "13306:3306"
    mem_limit: 2800M

  portal:
    image: eu.gcr.io/powop-1349/portal:latest
    env_file:
      - src/main/resources/docker/env/common.env
    environment:
      - CDN_KEY
      - JPDA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n
    command:
      - catalina.sh
      - jpda
      - run
    links:
      - db
      - geoserver
      - solr
    mem_limit: 500M
    ports:
      - 8000:8000

  harvester:
    image: eu.gcr.io/powop-1349/harvester:latest
    env_file:
      - src/main/resources/docker/env/common.env
    environment:
      - CDN_KEY
      - JPDA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n
    command:
      - catalina.sh
      - jpda
      - run
    links:
      - db
      - geoserver
      - solr
    mem_limit: 2G
    ports:
      - 8001:8000

  ingress:
    image: eu.gcr.io/powop-1349/ingress:latest
    env_file:
      - src/main/resources/docker/env/common.env
    environment:
      PORTAL: portal
    links:
      - geoserver
      - harvester
      - portal
    ports:
      - "10080:80"
    mem_limit: 50M
    volumes:
      - ./powo-portal/src/main/frontend/dist/css:/www/data/css
      - ./powo-portal/src/main/frontend/dist/js:/www/data/js

  solr:
    image: eu.gcr.io/powop-1349/solr:latest
    ports:
      - "18983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/powop/data
    mem_limit: 800M

  geoserver:
    image: eu.gcr.io/powop-1349/geoserver:latest
    env_file: src/main/resources/docker/env/common.env
    links:
      - geodb
    ports:
      - "18080:8080"
    mem_limit: 1500M
  geodb:
    image: eu.gcr.io/powop-1349/geodb:latest
    env_file:
      - src/main/resources/docker/env/common.env
      - src/main/resources/docker/env/geoserver.env
    mem_limit: 200M

volumes:
  portal_data: {}
  solr_data: {}


# Configuration for testing site variants

  # portal-col:
  #   image: eu.gcr.io/powop-1349/portal:latest
  #   env_file:
  #     - src/main/resources/docker/env/common.env
  #   environment:
  #     SITE_VARIANT: 'ColPlantASite'
  #   links:
  #     - db
  #     - geoserver
  #     - solr
  #   volumes:
  #     - ./powo-portal/target/powo-portal.war:/usr/local/tomcat/webapps/ROOT.war
  #   mem_limit: 500M

  # ingress-col:
  #   image: eu.gcr.io/powop-1349/ingress:latest
  #   env_file:
  #     - src/main/resources/docker/env/common.env
  #   environment:
  #     PORTAL: portal-col
  #   links:
  #     - geoserver
  #     - harvester
  #     - portal-col
  #   volumes:
  #     - ./powo-static/target/static/css:/usr/local/apache2/htdocs/css
  #     - ./powo-static/target/static/fonts:/usr/local/apache2/htdocs/fonts
  #     - ./powo-static/target/static/img:/usr/local/apache2/htdocs/img
  #     - ./powo-static/target/static/js:/usr/local/apache2/htdocs/js
  #   ports:
  #     - "20080:80"
  #   mem_limit: 50M
  #     - "18983:8983"
  #   volumes:
  #     - solr_data:/opt/solr/server/solr/powop/data
  #   mem_limit: 800M
