version: '2'
services:
  db:
    image: eu.gcr.io/powop-1349/db:latest
    env_file:
      - src/main/resources/docker/env/common.env
      - src/main/resources/docker/env/portal.env
    volumes:
      - portal_data:/var/lib/mysql
    ports:
      - "13306:3306"
  portal:
    image: eu.gcr.io/powop-1349/portal:latest
    env_file:
      - src/main/resources/docker/env/common.env
    links:
      - db
      - geoserver
      - solr
    volumes:
      - ./powo-portal/target/powo-portal.war:/usr/local/tomcat/webapps/ROOT.war

  portalColplanta:
    image: eu.gcr.io/powop-1349/portal:latest
    env_file:
      - src/main/resources/docker/env/common.env
    environment:
      SITE_VARIANT: ColPlantASite
    links:
      - db
      - geoserver
      - solr
    volumes:
      - ./powo-portal/target/powo-portal.war:/usr/local/tomcat/webapps/ROOT.war

  harvester:
    image: eu.gcr.io/powop-1349/harvester:latest
    env_file:
      - src/main/resources/docker/env/common.env
    links:
      - db
      - geoserver
      - solr
    volumes:
      - ./powo-harvest/target/powo-harvest.war:/usr/local/tomcat/webapps/harvester.war

  apache:
    image: eu.gcr.io/powop-1349/apache:latest
    env_file:
      - src/main/resources/docker/env/common.env
    links:
      - geoserver
      - harvester
      - portal
      - portal_colplanta
    volumes:
      - ./powo-portal/src/main/frontend/dist/css:/usr/local/apache2/htdocs/css
      - ./powo-portal/src/main/frontend/dist/fonts:/usr/local/apache2/htdocs/fonts
      - ./powo-portal/src/main/frontend/dist/img:/usr/local/apache2/htdocs/img
      - ./powo-portal/src/main/frontend/dist/js:/usr/local/apache2/htdocs/js
      - ./powo-static/src/main/tiles/:/usr/local/apache2/htdocs/tiles
    ports:
      - "10080:80"
    mem_limit: 200M

  solr:
    image: eu.gcr.io/powop-1349/solr:latest
    ports:
      - "18983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/powop/data

  geoserver:
    image: eu.gcr.io/powop-1349/geoserver:latest
    env_file: src/main/resources/docker/env/common.env
    links:
      - geodb
    ports:
      - "18080:8080"
    mem_limit: 1G

  geodb:
    image: eu.gcr.io/powop-1349/geodb:latest
    env_file:
      - src/main/resources/docker/env/common.env
      - src/main/resources/docker/env/geoserver.env


volumes:
  portal_data: {}
  solr_data: {}
