/*
 * This is eMonocot, a global online biodiversity information resource.
 *
 * Copyright © 2011–2015 The Board of Trustees of the Royal Botanic Gardens, Kew and The University of Oxford
 *
 * eMonocot is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * eMonocot is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
 * the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * The complete text of the GNU Affero General Public License is in the source repository as the file
 * ‘COPYING’.  It is also available from <http://www.gnu.org/licenses/>.
 */
package org.emonocot.model.constants;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableSet;

/**
 * @see http://rs.gbif.org/vocabulary/gbif/description_type.xml
 */
public enum DescriptionType {

	// standard gbif-extension types
	general("http://rs.gbif.org/vocabulary/gbif/descriptionType/general", "general"),
	diagnostic("http://rs.gbif.org/vocabulary/gbif/descriptionType/diagnostic", "diagnostic"),
	morphology("http://rs.gbif.org/vocabulary/gbif/descriptionType/morphology", "morphology"),
	habit("http://rs.gbif.org/vocabulary/gbif/descriptionType/habit", "morphology:general:habit"),
	cytology("http://rs.gbif.org/vocabulary/gbif/descriptionType/cytology", "cytology"),
	physiology("http://rs.gbif.org/vocabulary/gbif/descriptionType/physiology", "physiology"),
	size("http://rs.gbif.org/vocabulary/gbif/descriptionType/size", "size"),
	weight("http://rs.gbif.org/vocabulary/gbif/descriptionType/weight", "weight"),
	lifespan("http://rs.gbif.org/vocabulary/gbif/descriptionType/lifespan", "lifespan"),
	lifetime("http://rs.gbif.org/vocabulary/gbif/descriptionType/lifetime", "lifetime"),
	biology("http://rs.gbif.org/vocabulary/gbif/descriptionType/biology", "biology"),
	ecology("http://rs.gbif.org/vocabulary/gbif/descriptionType/ecology", "ecology"),
	habitat("http://rs.gbif.org/vocabulary/gbif/descriptionType/habitat", "habitat"),
	distribution("http://rs.gbif.org/vocabulary/gbif/descriptionType/distribution", "distribution"),
	reproduction("http://rs.gbif.org/vocabulary/gbif/descriptionType/reproduction", "reproduction"),
	conservation("http://rs.gbif.org/vocabulary/gbif/descriptionType/conservation", "conservation"),
	use("http://rs.gbif.org/vocabulary/gbif/descriptionType/use", "use"),
	dispersal( "http://rs.gbif.org/vocabulary/gbif/descriptionType/dispersal", "dispersal"),
	cyclicity("http://rs.gbif.org/vocabulary/gbif/descriptionType/cyclicity", "cyclicity"),
	lifecycle("http://rs.gbif.org/vocabulary/gbif/descriptionType/lifecycle", "lifecycle"),
	migration("http://rs.gbif.org/vocabulary/gbif/descriptionType/migration", "migration"),
	growth( "http://rs.gbif.org/vocabulary/gbif/descriptionType/growth", "constructionalOrganisation:growth"),
	genetics("http://rs.gbif.org/vocabulary/gbif/descriptionType/genetics", "genetics"),
	chemistry("http://rs.gbif.org/vocabulary/gbif/descriptionType/chemistry", "chemistry"),
	diseases("http://rs.gbif.org/vocabulary/gbif/descriptionType/diseases", "diseases"),
	associations("http://rs.gbif.org/vocabulary/gbif/descriptionType/associations", "associations"),
	behaviour("http://rs.gbif.org/vocabulary/gbif/descriptionType/behaviour", "behaviour"),
	population("http://rs.gbif.org/vocabulary/gbif/descriptionType/population", "population"),
	management("http://rs.gbif.org/vocabulary/gbif/descriptionType/management", "management"),
	legislation("http://rs.gbif.org/vocabulary/gbif/descriptionType/legislation", "legislation"),
	threats("http://rs.gbif.org/vocabulary/gbif/descriptionType/threats", "threats"),
	typematerial("http://rs.gbif.org/vocabulary/gbif/descriptionType/typematerial", "typematerial"),
	typelocality("http://rs.gbif.org/vocabulary/gbif/descriptionType/typelocality", "typelocality"),
	phylogeny("http://rs.gbif.org/vocabulary/gbif/descriptionType/phylogeny", "phylogeny"),
	hybrids("http://rs.gbif.org/vocabulary/gbif/descriptionType/hybrids", "hybrids"),
	literature("http://rs.gbif.org/vocabulary/gbif/descriptionType/literature", "literature"),
	culture("http://rs.gbif.org/vocabulary/gbif/descriptionType/culture", "culture"),
	vernacular("http://rs.gbif.org/vocabulary/gbif/descriptionType/vernacular", "vernacular"),

	// non-standard description types
	concept("concept"),
	figures("figures"),
	floralDiagram("floralDiagram"),
	glossary("glossary"),
	note("note"),
	reference("reference"),
	morphologyGeneral("morphology:general"),
	morphologyGeneralAreoles("morphology:general:areoles"),
	morphologyGeneralBuds("morphology:general:buds"),
	morphologyGeneralColleters("morphology:general:colleters"),
	morphologyGeneralCystoliths("morphology:general:cystoliths"),
	morphologyGeneralExudate("morphology:general:exudate"),
	morphologyGeneralGlands("morphology:general:glands"),
	morphologyGeneralHabit("morphology:general:habit"),
	morphologyGeneralIndumentum("morphology:general:indumentum"),
	morphologyGeneralSpines("morphology:general:spines"),
	morphologyGeneralTendrils("morphology:general:tendrils"),
	morphologyGeneralThallus("morphology:general:thallus"),
	morphologyGeneralTraps("morphology:general:traps"),
	morphologyLeaf("morphology:leaf"),
	morphologyLeafScaleLeaves("morphology:leaf:scaleLeaves"),
	morphologyLeafLamina("morphology:leaf:lamina"),
	morphologyLeafLaminaMargins("morphology:leaf:lamina:margins"),
	morphologyLeafLaminaVenation("morphology:leaf:lamina:venation"),
	morphologyLeafLeafSheaths("morphology:leaf:leaf-sheaths"),
	morphologyLeafLigule("morphology:leaf:ligule"),
	morphologyLeafLigules("morphology:leaf:ligules"),
	morphologyLeafOcrea("morphology:leaf:ocrea"),
	morphologyLeafPetiole("morphology:leaf:petiole"),
	morphologyLeafStipules("morphology:leaf:stipules"),
	morphologyReproductive("morphology:reproductive"),
	morphologyReproductiveCones("morphology:reproductive:cones"),
	morphologyReproductiveFlowers("morphology:reproductive:flowers"),
	morphologyReproductiveFlowersAndroecium("morphology:reproductive:flowers:androecium"),
	morphologyReproductiveFlowersAndrogynophore("morphology:reproductive:flowers:androgynophore"),
	morphologyReproductiveFlowersBracts("morphology:reproductive:flowers:bracts"),
	morphologyReproductiveFlowersBuds("morphology:reproductive:flowers:buds"),
	morphologyReproductiveFlowersCalyx("morphology:reproductive:flowers:calyx"),
	morphologyReproductiveFlowersColumn("morphology:reproductive:flowers:column"),
	morphologyReproductiveFlowersCorolla("morphology:reproductive:flowers:corolla"),
	morphologyReproductiveFlowersCorona("morphology:reproductive:flowers:corona"),
	morphologyReproductiveFlowersDisc("morphology:reproductive:flowers:disc"),
	morphologyReproductiveFlowersEpicalyx("morphology:reproductive:flowers:epicalyx"),
	morphologyReproductiveFlowersGynoecium("morphology:reproductive:flowers:gynoecium"),
	morphologyReproductiveFlowersGynophore("morphology:reproductive:flowers:gynophore"),
	morphologyReproductiveFlowersHypanthium("morphology:reproductive:flowers:hypanthium"),
	morphologyReproductiveFlowersLodicules("morphology:reproductive:flowers:lodicules"),
	morphologyReproductiveFlowersNectaries("morphology:reproductive:flowers:nectaries"),
	morphologyReproductiveFlowersPedicel("morphology:reproductive:flowers:pedicel"),
	morphologyReproductiveFlowersPerianth("morphology:reproductive:flowers:perianth"),
	morphologyReproductiveFlowersReceptacle("morphology:reproductive:flowers:receptacle"),
	morphologyReproductiveFlowersSterileParts("morphology:reproductive:flowers:sterileParts"),
	morphologyReproductiveFruits("morphology:reproductive:fruits"),
	morphologyReproductiveGermination("morphology:reproductive:germination"),
	morphologyReproductiveInflorescences("morphology:reproductive:inflorescences"),
	morphologyReproductiveInflorescencesBracts("morphology:reproductive:inflorescences:bracts"),
	morphologyReproductiveInflorescencesPeduncle("morphology:reproductive:inflorescences:peduncle"),
	morphologyReproductiveInflorescencesScape("morphology:reproductive:inflorescences:scape"),
	morphologyReproductiveInflorescencesSpikelets("morphology:reproductive:inflorescences:spikelets"),
	morphologyReproductiveInflorescencesSpikeletsPedicelled("morphology:reproductive:inflorescences:spikelets:pedicelled"),
	morphologyReproductiveInflorescencesSpikeletsSessile("morphology:reproductive:inflorescences:spikelets:sessile"),
	morphologyReproductiveInflorescencesSpikeletsSubsessile("morphology:reproductive:inflorescences:spikelets:subsessile"),
	morphologyReproductiveInfructescences("morphology:reproductive:infructescences"),
	morphologyReproductiveSeeds("morphology:reproductive:seeds"),
	morphologyRoot("morphology:root"),
	morphologyStem("morphology:stem"),
	morphologyStemCladodes("morphology:stem:cladodes"),
	vegetativeMultiplicationBulbils("vegetativeMultiplication:bulbils"),
	vegetativeMultiplicationBulbs("vegetativeMultiplication:bulbs"),
	vegetativeMultiplicationCorms("vegetativeMultiplication:corms"),
	vegetativeMultiplicationPseudobulbs("vegetativeMultiplication:pseudobulbs"),
	vegetativeMultiplicationRhizome("vegetativeMultiplication:rhizome"),
	vegetativeMultiplicationTubers("vegetativeMultiplication:tubers"),
	morphologyGeneralWood("morphology:general:wood"),
	vegetativeMultiplication("vegetativeMultiplication"),
	constructionalOrganisationGrowth("constructionalOrganisation:growth"),
	constructionalOrganisation("constructionalOrganisation"),
	morphologyGeneralScales("morphology:general:scales"),
	
	useAnimalFoodBees("use:animalFood:bees"),
	useAnimalFoodBeesBees("use:animalFood:bees:bees"),
	useAnimalFoodFlowersBees("use:animalFood:flowers:bees"),
	useAnimalFoodFlowersDomesticatedBirds("use:animalFood:flowers:domesticatedBirds"),
	useAnimalFoodFlowersOtherAnimals("use:animalFood:flowers:otherAnimals"),
	useAnimalFoodFlowersOtherBirds("use:animalFood:flowers:otherBirds"),
	useAnimalFoodFlowersOtherGameAnimals("use:animalFood:flowers:otherGameAnimals"),
	useAnimalFoodFruits("use:animalFood:fruits"),
	useAnimalFoodFruitsGoats("use:animalFood:fruits:goats"),
	useAnimalFoodFruitsOtherAnimals("use:animalFood:fruits:otherAnimals"),
	useAnimalFoodFruitsOtherBirds("use:animalFood:fruits:otherBirds"),
	useAnimalFoodFruitsOtherDomesticatedAnimalsLivestock("use:animalFood:fruits:otherDomesticatedAnimalsLivestock"),
	useAnimalFoodFruitsOtherFarmAnimals("use:animalFood:fruits:otherFarmAnimals"),
	useAnimalFoodFruitsOtherGameAnimals("use:animalFood:fruits:otherGameAnimals"),
	useAnimalFoodFruitsSheep("use:animalFood:fruits:sheep"),
	useAnimalFoodFruitsUnspecifiedAnimal("use:animalFood:fruits:unspecifiedAnimal"),
	useAnimalFoodGrainsCerealsDomesticatedBirds("use:animalFood:grainsCereals:domesticatedBirds"),
	useAnimalFoodGrainsCerealsOtherBirds("use:animalFood:grainsCereals:otherBirds"),
	useAnimalFoodHerbage("use:animalFood:herbage"),
	useAnimalFoodHerbageBees("use:animalFood:herbage:bees"),
	useAnimalFoodHerbageCamels("use:animalFood:herbage:camels"),
	useAnimalFoodHerbageCattle("use:animalFood:herbage:cattle"),
	useAnimalFoodHerbageDomesticatedBirds("use:animalFood:herbage:domesticatedBirds"),
	useAnimalFoodHerbageDomesticatedPigs("use:animalFood:herbage:domesticatedPigs"),
	useAnimalFoodHerbageDonkeys("use:animalFood:herbage:donkeys"),
	useAnimalFoodHerbageEdibleInsectsCaterpillarsLarvae("use:animalFood:herbage:edibleInsectsCaterpillarsLarvae"),
	useAnimalFoodHerbageFish("use:animalFood:herbage:fish"),
	useAnimalFoodHerbageGoats("use:animalFood:herbage:goats"),
	useAnimalFoodHerbageHorses("use:animalFood:herbage:horses"),
	useAnimalFoodHerbageOtherAnimals("use:animalFood:herbage:otherAnimals"),
	useAnimalFoodHerbageOtherBirds("use:animalFood:herbage:otherBirds"),
	useAnimalFoodHerbageOtherDomesticatedAnimalsLivestock("use:animalFood:herbage:otherDomesticatedAnimalsLivestock"),
	useAnimalFoodHerbageOtherFarmAnimals("use:animalFood:herbage:otherFarmAnimals"),
	useAnimalFoodHerbageOtherGameAnimals("use:animalFood:herbage:otherGameAnimals"),
	useAnimalFoodHerbageSheep("use:animalFood:herbage:sheep"),
	useAnimalFoodHerbageSilkworms("use:animalFood:herbage:silkworms"),
	useAnimalFoodHerbageUnspecifiedAnimal("use:animalFood:herbage:unspecifiedAnimal"),
	useAnimalFoodOilsFatsAnts("use:animalFood:oilsFats:ants"),
	useAnimalFoodOtherAnimalFoodType("use:animalFood:otherAnimalFoodType"),
	useAnimalFoodOtherAnimalFoodTypeAnts("use:animalFood:otherAnimalFoodType:ants"),
	useAnimalFoodOtherAnimalFoodTypeCamels("use:animalFood:otherAnimalFoodType:camels"),
	useAnimalFoodOtherAnimalFoodTypeGoats("use:animalFood:otherAnimalFoodType:goats"),
	useAnimalFoodOtherAnimalFoodTypeHorses("use:animalFood:otherAnimalFoodType:horses"),
	useAnimalFoodOtherAnimalFoodTypeLacInsects("use:animalFood:otherAnimalFoodType:lacInsects"),
	useAnimalFoodOtherAnimalFoodTypeOtherAnimals("use:animalFood:otherAnimalFoodType:otherAnimals"),
	useAnimalFoodOtherAnimalFoodTypeOtherBirds("use:animalFood:otherAnimalFoodType:otherBirds"),
	useAnimalFoodOtherAnimalFoodTypeOtherFarmAnimals("use:animalFood:otherAnimalFoodType:otherFarmAnimals"),
	useAnimalFoodOtherAnimalFoodTypeOtherGameAnimals("use:animalFood:otherAnimalFoodType:otherGameAnimals"),
	useAnimalFoodOtherAnimalFoodTypeUnspecifiedAnimal("use:animalFood:otherAnimalFoodType:unspecifiedAnimal"),
	useAnimalFoodPulsesCattle("use:animalFood:pulses:cattle"),
	useAnimalFoodPulsesOtherAnimals("use:animalFood:pulses:otherAnimals"),
	useAnimalFoodPulsesOtherGameAnimals("use:animalFood:pulses:otherGameAnimals"),
	useAnimalFoodPulsesUnspecifiedAnimal("use:animalFood:pulses:unspecifiedAnimal"),
	useAnimalFoodResiduesByproductsFromIndustry("use:animalFood:residuesByproductsFromIndustry"),
	useAnimalFoodRootsOtherFarmAnimals("use:animalFood:roots:otherFarmAnimals"),
	useAnimalFoodRootsOtherGameAnimals("use:animalFood:roots:otherGameAnimals"),
	useAnimalFoodUnspecifiedAnimalFoodType("use:animalFood:unspecifiedAnimalFoodType"),
	useAnimalFoodUnspecifiedAnimalFoodTypeBees("use:animalFood:unspecifiedAnimalFoodType:bees"),
	useAnimalFoodUnspecifiedAnimalFoodTypeFarmBirds("use:animalFood:unspecifiedAnimalFoodType:farmBirds"),
	useAnimalFoodUnspecifiedAnimalFoodTypeUnspecifiedAnimal("use:animalFood:unspecifiedAnimalFoodType:unspecifiedAnimal"),
	useAnimalFoodUnspecifiedAnimalUnspecifiedAnimal("use:animalFood:unspecifiedAnimal:unspecifiedAnimal"),
	useEnvironmentalUseAgroforestry("use:environmentalUse:agroforestry"),
	useEnvironmentalUseBoundaryBarrierSupportPlants("use:environmentalUse:boundaryBarrierSupportPlants"),
	useEnvironmentalUseBoundaryBarrierSupportPlantsConstructions("use:environmentalUse:boundaryBarrierSupportPlants:constructions"),
	useEnvironmentalUseCompanionPlants("use:environmentalUse:companionPlants"),
	useEnvironmentalUseErosionControl("use:environmentalUse:erosionControl"),
	useEnvironmentalUseErosionControlTextiles("use:environmentalUse:erosionControl:textiles"),
	useEnvironmentalUseFirebreaks("use:environmentalUse:firebreaks"),
	useEnvironmentalUseIndicatorPlants("use:environmentalUse:indicatorPlants"),
	useEnvironmentalUseOrnamentals("use:environmentalUse:ornamentals"),
	useEnvironmentalUseOrnamentalsPigments("use:environmentalUse:ornamentals:pigments"),
	useEnvironmentalUseOrnamentalsUnspecifiedAnimal("use:environmentalUse:ornamentals:unspecifiedAnimal"),
	useEnvironmentalUseOtherEnvironmentalUses("use:environmentalUse:otherEnvironmentalUses"),
	useEnvironmentalUsePollutionControl("use:environmentalUse:pollutionControl"),
	useEnvironmentalUsePollutionControlUnspecifiedAnimal("use:environmentalUse:pollutionControl:unspecifiedAnimal"),
	useEnvironmentalUseRevegetation("use:environmentalUse:revegetation"),
	useEnvironmentalUseShadeShelter("use:environmentalUse:shadeShelter"),
	useEnvironmentalUseSoilImprovers("use:environmentalUse:soilImprovers"),
	useEnvironmentalUseSoilImproversUnspecifiedAnimal("use:environmentalUse:soilImprovers:unspecifiedAnimal"),
	useEnvironmentalUseUnspecifiedEnvironmentalUses("use:environmentalUse:unspecifiedEnvironmentalUses"),
	useFoodCereals("use:food:cereals"),
	useFoodFoodAdditives("use:food:foodAdditives"),
	useFoodFruits("use:food:fruits [dessertFruits]"),
	useFoodGumsMucilagesResins("use:food:gumsMucilagesResins"),
	useFoodNuts("use:food:nuts"),
	useFoodOilsFats("use:food:oilsFats"),
	useFoodOtherFoodType("use:food:otherFoodType"),
	useFoodPseudocereals("use:food:pseudocereals"),
	useFoodPulses("use:food:pulses"),
	useFoodStarches("use:food:starches"),
	useFoodSugars("use:food:sugars"),
	useFoodUnspecifiedFood("use:food:unspecifiedFood"),
	useFoodUnspecifiedFoodType("use:food:unspecifiedFoodType"),
	useFoodVegetables("use:food:vegetables"),
	useFuelCharcoal("use:fuel:charcoal"),
	useFuelFuelwood("use:fuel:fuelwood"),
	useFuelFuelwoodFurniture("use:fuel:fuelwood:furniture"),
	useFuelNonWoodyFuel("use:fuel:nonWoodyFuel"),
	useFuelPetroleumSubstitutes("use:fuel:petroleumSubstitutesAlcoholsEtc."),
	useFuelTinder("use:fuel:tinder"),
	useFuelTinderOtherProducts("use:fuel:tinder:otherProducts"),
	useFuelUnspecifiedFuelType("use:fuel:unspecifiedFuelType"),
	useMaterialsAlcohols("use:materials:alcohols"),
	useMaterialsAlcoholsOtherProducts("use:materials:alcohols:otherProducts"),
	useMaterialsCaneRattanBambooReedWickerEtcBasketry("use:materials:caneRattanBambooReedWickerEtc:basketry"),
	useMaterialsCaneRattanBambooReedWickerEtcConstructions("use:materials:caneRattanBambooReedWickerEtc:constructions"),
	useMaterialsCaneRattanBambooReedWickerEtcFishingEquipment("use:materials:caneRattanBambooReedWickerEtc:fishingEquipment"),
	useMaterialsCaneRattanBambooReedWickerEtcFurnishings("use:materials:caneRattanBambooReedWickerEtc:furnishings"),
	useMaterialsCaneRattanBambooReedWickerEtcFurniture("use:materials:caneRattanBambooReedWickerEtc:furniture"),
	useMaterialsCaneRattanBambooReedWickerEtcOtherProducts("use:materials:caneRattanBambooReedWickerEtc:otherProducts"),
	useMaterialsCaneRattanBambooReedWickerEtcRoofs("use:materials:caneRattanBambooReedWickerEtc:roofs"),
	useMaterialsCaneRattanBambooReedWickerEtcTools("use:materials:caneRattanBambooReedWickerEtc:tools"),
	useMaterialsCorkCorkSubstitutes("use:materials:corkCorkSubstitutes"),
	useMaterialsEssentialOils("use:materials:essentialOils"),
	useMaterialsEssentialOilsCosmetics("use:materials:essentialOils:cosmetics"),
	useMaterialsEssentialOilsLubricants("use:materials:essentialOils:lubricants"),
	useMaterialsEssentialOilsPerfumes("use:materials:essentialOils:perfumes"),
	useMaterialsEssentialOilsPersonalItems("use:materials:essentialOils:personalItems"),
	useMaterialsEssentialOilsUnspecifiedProduct("use:materials:essentialOils:unspecifiedProduct"),
	useMaterialsEssentialOilsUnspecifiedProducts("use:materials:essentialOils:unspecifiedProducts"),
	useMaterialsFibres("use:materials:fibres"),
	useMaterialsFibresBasketry("use:materials:fibres:basketry"),
	useMaterialsFibresClothing("use:materials:fibres:clothing"),
	useMaterialsFibresConstructions("use:materials:fibres:constructions"),
	useMaterialsFibresFastenersClosures("use:materials:fibres:fastenersClosures"),
	useMaterialsFibresFishingEquipment("use:materials:fibres:fishingEquipment"),
	useMaterialsFibresFloors("use:materials:fibres:floors"),
	useMaterialsFibresFurnishings("use:materials:fibres:furnishings"),
	useMaterialsFibresFurniture("use:materials:fibres:furniture"),
	useMaterialsFibresHarnessesTack("use:materials:fibres:harnessesTack"),
	useMaterialsFibresMusicalInstruments("use:materials:fibres:musicalInstruments (expandNotes)"),
	useMaterialsFibresOtherProducts("use:materials:fibres:otherProducts"),
	useMaterialsFibresPersonalItems("use:materials:fibres:personalItems"),
	useMaterialsFibresTextiles("use:materials:fibres:textiles"),
	useMaterialsFibresTools("use:materials:fibres:tools"),
	useMaterialsFibresToysGames("use:materials:fibres:toysGames"),
	useMaterialsFibresUnspecifiedProduct("use:materials:fibres:unspecifiedProduct"),
	useMaterialsFibresUnspecifiedProducts("use:materials:fibres:unspecifiedProducts"),
	useMaterialsFibresWeapons("use:materials:fibres:weapons"),
	useMaterialsFibresWoodProducts("use:materials:fibres:woodProducts"),
	useMaterialsGumsResins("use:materials:gumsResins"),
	useMaterialsGumsResinsAdhesives("use:materials:gumsResins:adhesives"),
	useMaterialsGumsResinsCleansers("use:materials:gumsResins:cleansers"),
	useMaterialsGumsResinsCoatings("use:materials:gumsResins:coatings"),
	useMaterialsGumsResinsCosmetics("use:materials:gumsResins:cosmetics"),
	useMaterialsGumsResinsEmulsifiers("use:materials:gumsResins:emulsifiers"),
	useMaterialsGumsResinsGellingAgents("use:materials:gumsResins:gellingAgents"),
	useMaterialsGumsResinsIncense("use:materials:gumsResins:incense"),
	useMaterialsGumsResinsOtherProducts("use:materials:gumsResins:otherProducts"),
	useMaterialsGumsResinsPersonalItems("use:materials:gumsResins:personalItems"),
	useMaterialsGumsResinsPurifiers("use:materials:gumsResins:purifiers (non-waterFood)"),
	useMaterialsGumsResinsUnspecifiedProduct("use:materials:gumsResins:unspecifiedProduct"),
	useMaterialsGumsResinsUnspecifiedProducts("use:materials:gumsResins:unspecifiedProducts"),
	useMaterialsLatexRubber("use:materials:latexRubber"),
	useMaterialsLatexRubberMusicalInstruments("use:materials:latexRubber:musicalInstruments (expandNotes)"),
	useMaterialsLatexRubberOtherProducts("use:materials:latexRubber:otherProducts"),
	useMaterialsLatexRubberUnspecifiedProduct("use:materials:latexRubber:unspecifiedProduct"),
	useMaterialsLatexRubberUnspecifiedProducts("use:materials:latexRubber:unspecifiedProducts"),
	useMaterialsLipids("use:materials:lipids (fats &Oils)"),
	useMaterialsLipidsCleansers("use:materials:lipids (fats &Oils):cleansers"),
	useMaterialsLipidsCosmetics("use:materials:lipids (fats &Oils):cosmetics"),
	useMaterialsLipidsLubricants("use:materials:lipids (fats &Oils):lubricants"),
	useMaterialsLipidsOtherProducts("use:materials:lipids (fats &Oils):otherProducts"),
	useMaterialsLipidsPersonalItems("use:materials:lipids (fats &Oils):personalItems"),
	useMaterialsOtherChemicals("use:materials:otherChemicals"),
	useMaterialsOtherChemicalsCleansers("use:materials:otherChemicals:cleansers"),
	useMaterialsOtherChemicalsFermentationAgents("use:materials:otherChemicals:fermentationAgents (non-food)"),
	useMaterialsOtherChemicalsOtherProducts("use:materials:otherChemicals:otherProducts"),
	useMaterialsOtherChemicalsPerfumes("use:materials:otherChemicals:perfumes"),
	useMaterialsOtherMaterials("use:materials:otherMaterials"),
	useMaterialsOtherMaterialsBeads("use:materials:otherMaterials:beads"),
	useMaterialsOtherMaterialsCleansers("use:materials:otherMaterials:cleansers"),
	useMaterialsOtherMaterialsConstructions("use:materials:otherMaterials:constructions"),
	useMaterialsOtherMaterialsContainersHolders("use:materials:otherMaterials:containersHolders"),
	useMaterialsOtherMaterialsCosmetics("use:materials:otherMaterials:cosmetics"),
	useMaterialsOtherMaterialsEmulsifiers("use:materials:otherMaterials:emulsifiers"),
	useMaterialsOtherMaterialsFishingEquipment("use:materials:otherMaterials:fishingEquipment"),
	useMaterialsOtherMaterialsFurnishings("use:materials:otherMaterials:furnishings"),
	useMaterialsOtherMaterialsFurniture("use:materials:otherMaterials:furniture"),
	useMaterialsOtherMaterialsIncense("use:materials:otherMaterials:incense"),
	useMaterialsOtherMaterialsMusicalInstruments("use:materials:otherMaterials:musicalInstruments (expandNotes)"),
	useMaterialsOtherMaterialsOtherProducts("use:materials:otherMaterials:otherProducts"),
	useMaterialsOtherMaterialsPaper("use:materials:otherMaterials:paper"),
	useMaterialsOtherMaterialsPaperSubstitutes("use:materials:otherMaterials:paperSubstitutes"),
	useMaterialsOtherMaterialsPersonalItems("use:materials:otherMaterials:personalItems"),
	useMaterialsOtherMaterialsTools("use:materials:otherMaterials:tools"),
	useMaterialsOtherMaterialsUnspecifiedProduct("use:materials:otherMaterials:unspecifiedProduct"),
	useMaterialsOtherMaterialsWeapons("use:materials:otherMaterials:weapons"),
	useMaterialsOtherMaterialsWoodProducts("use:materials:otherMaterials:woodProducts"),
	useMaterialsTanninsDyestuffs("use:materials:tanninsDyestuffs"),
	useMaterialsTanninsDyestuffsAbrasives("use:materials:tanninsDyestuffs:abrasives"),
	useMaterialsTanninsDyestuffsBasketry("use:materials:tanninsDyestuffs:basketry"),
	useMaterialsTanninsDyestuffsCoatings("use:materials:tanninsDyestuffs:coatings"),
	useMaterialsTanninsDyestuffsCosmetics("use:materials:tanninsDyestuffs:cosmetics"),
	useMaterialsTanninsDyestuffsFloors("use:materials:tanninsDyestuffs:floors"),
	useMaterialsTanninsDyestuffsOtherProducts("use:materials:tanninsDyestuffs:otherProducts"),
	useMaterialsTanninsDyestuffsPigments("use:materials:tanninsDyestuffs:pigments"),
	useMaterialsTanninsDyestuffsTanninsDyestuffs("use:materials:tanninsDyestuffs:tanninsDyestuffs"),
	useMaterialsTanninsDyestuffsTextiles("use:materials:tanninsDyestuffs:textiles"),
	useMaterialsTanninsDyestuffsUnspecifiedProduct("use:materials:tanninsDyestuffs:unspecifiedProduct"),
	useMaterialsTanninsDyestuffsUnspecifiedProducts("use:materials:tanninsDyestuffs:unspecifiedProducts"),
	useMaterialsUnspecifiedMaterialsChemicals("use:materials:unspecifiedMaterialsChemicals"),
	useMaterialsUnspecifiedMaterialsChemicalsAdhesives("use:materials:unspecifiedMaterialsChemicals:adhesives"),
	useMaterialsUnspecifiedMaterialsChemicalsBoard("use:materials:unspecifiedMaterialsChemicals:board"),
	useMaterialsUnspecifiedMaterialsChemicalsBuildings("use:materials:unspecifiedMaterialsChemicals:buildings"),
	useMaterialsUnspecifiedMaterialsChemicalsClarifiers("use:materials:unspecifiedMaterialsChemicals:clarifiers (notForWaterFood)"),
	useMaterialsUnspecifiedMaterialsChemicalsCleansers("use:materials:unspecifiedMaterialsChemicals:cleansers"),
	useMaterialsUnspecifiedMaterialsChemicalsConstructions("use:materials:unspecifiedMaterialsChemicals:constructions"),
	useMaterialsUnspecifiedMaterialsChemicalsCosmetics("use:materials:unspecifiedMaterialsChemicals:cosmetics"),
	useMaterialsUnspecifiedMaterialsChemicalsFishingEquipment("use:materials:unspecifiedMaterialsChemicals:fishingEquipment"),
	useMaterialsUnspecifiedMaterialsChemicalsFurniture("use:materials:unspecifiedMaterialsChemicals:furniture"),
	useMaterialsUnspecifiedMaterialsChemicalsIncense("use:materials:unspecifiedMaterialsChemicals:incense"),
	useMaterialsUnspecifiedMaterialsChemicalsMusicalInstruments("use:materials:unspecifiedMaterialsChemicals:musicalInstruments (expandNotes)"),
	useMaterialsUnspecifiedMaterialsChemicalsOtherProducts("use:materials:unspecifiedMaterialsChemicals:otherProducts"),
	useMaterialsUnspecifiedMaterialsChemicalsPerfumes("use:materials:unspecifiedMaterialsChemicals:perfumes"),
	useMaterialsUnspecifiedMaterialsChemicalsPersonalItems("use:materials:unspecifiedMaterialsChemicals:personalItems"),
	useMaterialsUnspecifiedMaterialsChemicalsPigments("use:materials:unspecifiedMaterialsChemicals:pigments"),
	useMaterialsUnspecifiedMaterialsChemicalsRoofs("use:materials:unspecifiedMaterialsChemicals:roofs"),
	useMaterialsUnspecifiedMaterialsChemicalsTools("use:materials:unspecifiedMaterialsChemicals:tools"),
	useMaterialsUnspecifiedMaterialsChemicalsUnspecifiedProducts("use:materials:unspecifiedMaterialsChemicals:unspecifiedProducts"),
	useMaterialsUnspecifiedMaterialsChemicalsVehicles("use:materials:unspecifiedMaterialsChemicals:vehicles"),
	useMaterialsUnspecifiedMaterialsChemicalsWalls("use:materials:unspecifiedMaterialsChemicals:walls"),
	useMaterialsWaxesUnspecifiedProducts("use:materials:waxes:unspecifiedProducts"),
	useMaterialsWood("use:materials:wood"),
	useMaterialsWoodBasketry("use:materials:wood:basketry"),
	useMaterialsWoodBoard("use:materials:wood:board"),
	useMaterialsWoodBuildings("use:materials:wood:buildings"),
	useMaterialsWoodConstructions("use:materials:wood:constructions"),
	useMaterialsWoodContainersHolders("use:materials:wood:containersHolders"),
	useMaterialsWoodFastenersClosures("use:materials:wood:fastenersClosures"),
	useMaterialsWoodFishingEquipment("use:materials:wood:fishingEquipment"),
	useMaterialsWoodFloors("use:materials:wood:floors"),
	useMaterialsWoodFurnishings("use:materials:wood:furnishings"),
	useMaterialsWoodFurniture("use:materials:wood:furniture"),
	useMaterialsWoodJoinery("use:materials:wood:joinery"),
	useMaterialsWoodMachineParts("use:materials:wood:machineParts"),
	useMaterialsWoodModels("use:materials:wood:models"),
	useMaterialsWoodMusicalInstruments("use:materials:wood:musicalInstruments (expandNotes)"),
	useMaterialsWoodOtherProducts("use:materials:wood:otherProducts"),
	useMaterialsWoodPaper("use:materials:wood:paper"),
	useMaterialsWoodPerfumes("use:materials:wood:perfumes"),
	useMaterialsWoodPersonalItems("use:materials:wood:personalItems"),
	useMaterialsWoodRoofs("use:materials:wood:roofs"),
	useMaterialsWoodScientificTechnicalEquipment("use:materials:wood:scientificTechnicalEquipment"),
	useMaterialsWoodSportsEquipment("use:materials:wood:sportsEquipment"),
	useMaterialsWoodTools("use:materials:wood:tools"),
	useMaterialsWoodToysGames("use:materials:wood:toysGames"),
	useMaterialsWoodUnspecifiedProduct("use:materials:wood:unspecifiedProduct"),
	useMaterialsWoodUnspecifiedProducts("use:materials:wood:unspecifiedProducts"),
	useMaterialsWoodVehicles("use:materials:wood:vehicles"),
	useMaterialsWoodWalls("use:materials:wood:walls"),
	useMaterialsWoodWeapons("use:materials:wood:weapons"),
	useMaterialsWoodWheels("use:materials:wood:wheels"),
	useMaterialsWoodWoodProducts("use:materials:wood:woodProducts"),
	useMedicinesAbnormalities("use:medicines:abnormalities"),
	useMedicinesAntifertiliyAgent("use:medicines:antifertiliyAgent"),
	useMedicinesBloodSystemDisorders("use:medicines:bloodSystemDisorders"),
	useMedicinesCirculatorySystemDisorders("use:medicines:circulatorySystemDisorders"),
	useMedicinesDigestiveSystemDisorders("use:medicines:digestiveSystemDisorders"),
	useMedicinesDigestiveSystemDisordersUnspecifiedAnimal("use:medicines:digestiveSystemDisorders:unspecifiedAnimal"),
	useMedicinesEndocrineSystemDisorders("use:medicines:endocrineSystemDisorders"),
	useMedicinesGenitourinarySystemDisorders("use:medicines:genitourinarySystemDisorders"),
	useMedicinesIllDefinedSymptoms("use:medicines:ill-definedSymptoms"),
	useMedicinesImmuneSystemDisorders("use:medicines:immuneSystemDisorders"),
	useMedicinesInfectionsInfestations("use:medicines:infectionsInfestations"),
	useMedicinesInfectionsInfestationsAnimalDiseaseControl("use:medicines:infectionsInfestations:animalDiseaseControl"),
	useMedicinesInfectionsInfestationsUnspecifiedAnimal("use:medicines:infectionsInfestations:unspecifiedAnimal"),
	useMedicinesInflammation("use:medicines:inflammation"),
	useMedicinesInjuries("use:medicines:injuries"),
	useMedicinesLocalCulturalDisorders("use:medicines:localCulturalDisorders"),
	useMedicinesMentalDisorders("use:medicines:mentalDisorders"),
	useMedicinesMetabolicSystemDisorders("use:medicines:metabolicSystemDisorders"),
	useMedicinesMuscularSkeletalSystemDisorders("use:medicines:muscular-skeletalSystemDisorders"),
	useMedicinesNeoplasms("use:medicines:neoplasms"),
	useMedicinesNervousSystemDisorders("use:medicines:nervousSystemDisorders"),
	useMedicinesNutritionalDisorders("use:medicines:nutritionalDisorders"),
	useMedicinesOtherMedicinalDisorders("use:medicines:otherMedicinalDisorders"),
	useMedicinesOtherMedicinalDisordersAnimalDiseaseControl("use:medicines:otherMedicinalDisorders:animalDiseaseControl"),
	useMedicinesPain("use:medicines:pain"),
	useMedicinesPoisonings("use:medicines:poisonings"),
	useMedicinesPregnancyBirthPuerpueriumDisorders("use:medicines:pregnancyBirthPuerpueriumDisorders"),
	useMedicinesRespiratorySystemDisorders("use:medicines:respiratorySystemDisorders"),
	useMedicinesSensorySystemDisorders("use:medicines:sensorySystemDisorders"),
	useMedicinesSensorySystemDisordersAnimalDiseaseControl("use:medicines:sensorySystemDisorders:animalDiseaseControl"),
	useMedicinesSkinSubcutaneousCellularTissueDisorders("use:medicines:skinSubcutaneousCellularTissueDisorders"),
	useMedicinesSkinSubcutaneousCellularTissueDisordersAnimalDiseaseControl("use:medicines:skinSubcutaneousCellularTissueDisorders:animalDiseaseControl"),
	useMedicinesUnspecifiedMedicinalDisorders("use:medicines:unspecifiedMedicinalDisorders"),
	useMedicinesUnspecifiedMedicinalDisordersMedicalAccessories("use:medicines:unspecifiedMedicinalDisorders:medicalAccessories"),
	usePoisonsAnimalDiseaseControl("use:poisons:animalDiseaseControl"),
	usePoisonsAnimalDiseaseControlAnimalDiseaseControl("use:poisons:animalDiseaseControl:animalDiseaseControl"),
	usePoisonsAnimalPestControl("use:poisons:animalPestControl"),
	usePoisonsAnimalPestControlAnimalDiseaseControl("use:poisons:animalPestControl:animalDiseaseControl"),
	usePoisonsAnimalPestControlAnimalPestControl("use:poisons:animalPestControl:animalPestControl"),
	usePoisonsAnimalPestControlStoredProductsProtection("use:poisons:animalPestControl:storedProductsProtection"),
	usePoisonsAnthelminticAnimalDiseaseControl("use:poisons:anthelmintic:animalDiseaseControl"),
	usePoisonsAnthelminticOtherUsesOfPoisons("use:poisons:anthelmintic:otherUsesOfPoisons"),
	usePoisonsAnthelminticUnspecifiedPoisonFunction("use:poisons:anthelmintic:unspecifiedPoisonFunction"),
	usePoisonsAntibacterialAnimalDiseaseControl("use:poisons:antibacterial:animalDiseaseControl"),
	usePoisonsAntiprotozoalAnimalDiseaseControl("use:poisons:antiprotozoal:animalDiseaseControl"),
	usePoisonsAntiviralAnimalDiseaseControl("use:poisons:antiviral:animalDiseaseControl"),
	usePoisonsFishPoison("use:poisons:fishPoison"),
	usePoisonsFishPoisonFishing("use:poisons:fishPoison:fishing"),
	usePoisonsFishingFishing("use:poisons:fishing:fishing"),
	usePoisonsHunting("use:poisons:hunting"),
	usePoisonsHuntingHunting("use:poisons:hunting:hunting"),
	usePoisonsInsecticidal("use:poisons:insecticidal"),
	usePoisonsInsecticidalAnimalPestControl("use:poisons:insecticidal:animalPestControl"),
	usePoisonsInsecticidalOtherUsesOfPoisons("use:poisons:insecticidal:otherUsesOfPoisons"),
	usePoisonsInsecticidalPlantPestControl("use:poisons:insecticidal:plantPestControl"),
	usePoisonsInsecticidalStoredProductsProtection("use:poisons:insecticidal:storedProductsProtection"),
	usePoisonsInsecticidalUnspecifiedPoisonFunction("use:poisons:insecticidal:unspecifiedPoisonFunction"),
	usePoisonsMammalianPoison("use:poisons:mammalianPoison"),
	usePoisonsMammalianPoisonHomicide("use:poisons:mammalianPoison:homicide"),
	usePoisonsMammalianPoisonHunting("use:poisons:mammalianPoison:hunting"),
	usePoisonsMammalianPoisonOtherUsesOfPoisons("use:poisons:mammalianPoison:otherUsesOfPoisons"),
	usePoisonsMammalianPoisonPlantPestControl("use:poisons:mammalianPoison:plantPestControl"),
	usePoisonsOtherPoisonTypeAnimalDiseaseControl("use:poisons:otherPoisonType:animalDiseaseControl"),
	usePoisonsOtherUsesOfPoisons("use:poisons:otherUsesOfPoisons"),
	usePoisonsOtherUsesOfPoisonsOtherUsesOfPoisons("use:poisons:otherUsesOfPoisons:otherUsesOfPoisons"),
	usePoisonsPlantDiseaseControl("use:poisons:plantDiseaseControl"),
	usePoisonsPlantDiseaseControlPlantDiseaseControl("use:poisons:plantDiseaseControl:plantDiseaseControl"),
	usePoisonsPlantPestControl("use:poisons:plantPestControl"),
	usePoisonsPlantPestControlPlantPestControl("use:poisons:plantPestControl:plantPestControl"),
	usePoisonsPoisonousPropertyNotActivelyUsed("use:poisons:poisonousPropertyNotActivelyUsed"),
	usePoisonsPoisonousPropertyNotActivelyUsedPoisonousPropertyNotActivelyUsed("use:poisons:poisonousPropertyNotActivelyUsed:poisonousPropertyNotActivelyUsed"),
	usePoisonsReptilePoison("use:poisons:reptilePoison"),
	usePoisonsUnspecifiedPoisonTypeAnimalDiseaseControl("use:poisons:unspecifiedPoisonType:animalDiseaseControl"),
	usePoisonsUnspecifiedPoisonTypeAnimalPestControl("use:poisons:unspecifiedPoisonType:animalPestControl"),
	usePoisonsUnspecifiedPoisonTypeHunting("use:poisons:unspecifiedPoisonType:hunting"),
	usePoisonsUnspecifiedPoisonTypePoisonourPropertyNotActivelyUsed("use:poisons:unspecifiedPoisonType:poisonourPropertyNotActivelyUsed"),
	usePoisonsUnspecifiedPoisonTypeUnspecifiedPoisonFunction("use:poisons:unspecifiedPoisonType:unspecifiedPoisonFunction"),
	useSocialUseAdulterants("use:socialUse:adulterants"),
	useSocialUseHallucinogens("use:socialUse:hallucinogens"),
	useSocialUseMasticatories("use:socialUse:masticatories"),
	useSocialUseMasticatoriesPersonalItems("use:socialUse:masticatories:personalItems"),
	useSocialUseOrnamentals("use:socialUse:ornamentals"),
	useSocialUseOtherSocialUses("use:socialUse:otherSocialUses"),
	useSocialUseSacredSpiritualPlants("use:socialUse:sacredSpiritualPlants"),
	useSocialUseSacredSpiritualPlantsFurniture("use:socialUse:sacredSpiritualPlants:furniture"),
	useSocialUseSedatives("use:socialUse:sedatives"),
	useSocialUseSmokingMaterials("use:socialUse:smokingMaterials"),
	useSocialUseSnuff("use:socialUse:snuff"),
	useSocialUseStimulants("use:socialUse:stimulants"),
	useSocialUseUnspecifiedSocialUses("use:socialUse:unspecifiedSocialUses"),
	useWeedImpactAgriculturalWeed("use:weedImpact:agriculturalWeed"),
	useWeedImpactRangelandPastureWeed("use:weedImpact:rangelandPastureWeed"),
	useWeedImpactUnspecifiedWeed("use:weedImpact:unspecifiedWeed"),

	// Second level non-standard types. They are separated so that they sort after everything else
	sexHermaphrodite("sex:hermaphrodite"),
	sexFemale("sex:female"),
	sexMale("sex:male"),
	sex("sex");

	public static final DescriptionType generalDescriptionType = habit;

	public static final ImmutableMap<String, Set<DescriptionType>> searchCategories = ImmutableMap.<String, Set<DescriptionType>>builder()
			.put("appearance", ImmutableSet.<DescriptionType>of(
					morphologyGeneral,
					morphologyGeneralAreoles,
					morphologyGeneralBuds,
					morphologyGeneralColleters,
					morphologyGeneralCystoliths,
					morphologyGeneralExudate,
					morphologyGeneralGlands,
					morphologyGeneralHabit,
					morphologyGeneralIndumentum,
					morphologyGeneralSpines,
					morphologyGeneralTendrils,
					morphologyGeneralThallus,
					morphologyGeneralTraps,
					morphologyRoot,
					morphologyStem,
					morphologyStemCladodes,
					morphologyGeneralWood,
					vegetativeMultiplication,
					constructionalOrganisationGrowth))
			.put("inflorescence", ImmutableSet.<DescriptionType>of(
					morphologyReproductiveCones,
					morphologyReproductiveInflorescences,
					morphologyReproductiveInflorescencesBracts,
					morphologyReproductiveInflorescencesPeduncle,
					morphologyReproductiveInflorescencesScape,
					morphologyReproductiveInflorescencesSpikelets,
					morphologyReproductiveInflorescencesSpikeletsPedicelled,
					morphologyReproductiveInflorescencesSpikeletsSessile,
					morphologyReproductiveInflorescencesSpikeletsSubsessile))
			.put("fruit", ImmutableSet.<DescriptionType>of(
					morphologyReproductiveFruits,
					morphologyReproductiveInfructescences))
			.put("leaves", ImmutableSet.<DescriptionType>of(
					morphologyLeaf,
					morphologyLeafScaleLeaves,
					morphologyLeafLamina,
					morphologyLeafLaminaMargins,
					morphologyLeafLaminaVenation,
					morphologyLeafLeafSheaths,
					morphologyLeafLigule,
					morphologyLeafLigules,
					morphologyLeafOcrea,
					morphologyLeafPetiole,
					morphologyLeafStipules))
			.put("flower", ImmutableSet.<DescriptionType>of(
					morphologyReproductive,
					morphologyReproductiveFlowers,
					morphologyReproductiveFlowersAndroecium,
					morphologyReproductiveFlowersAndrogynophore,
					morphologyReproductiveFlowersBracts,
					morphologyReproductiveFlowersBuds,
					morphologyReproductiveFlowersCalyx,
					morphologyReproductiveFlowersColumn,
					morphologyReproductiveFlowersCorolla,
					morphologyReproductiveFlowersCorona,
					morphologyReproductiveFlowersEpicalyx,
					morphologyReproductiveFlowersGynoecium,
					morphologyReproductiveFlowersGynophore,
					morphologyReproductiveFlowersHypanthium,
					morphologyReproductiveFlowersLodicules,
					morphologyReproductiveFlowersNectaries,
					morphologyReproductiveFlowersPedicel,
					morphologyReproductiveFlowersPerianth,
					morphologyReproductiveFlowersReceptacle,
					morphologyReproductiveFlowersSterileParts,
					morphologyReproductiveFlowersDisc))
			.put("seed", ImmutableSet.<DescriptionType>of(
					morphologyReproductiveGermination,
					morphologyReproductiveSeeds))
			.put("vegitativePropagation", ImmutableSet.<DescriptionType>of(
					vegetativeMultiplicationBulbils,
					vegetativeMultiplicationBulbs,
					vegetativeMultiplicationCorms,
					vegetativeMultiplicationPseudobulbs,
					vegetativeMultiplicationRhizome,
					vegetativeMultiplicationTubers))
			.build();

	private String uri;

	private String term;

	private DescriptionType(final String newUri, String newTerm) {
		this.uri = newUri;
		this.term = newTerm;
	}

	private DescriptionType(final String newTerm) {
		this.term = newTerm;
	}

	/**
	 *
	 * @param uri The uri being converted into a Feature
	 * @return the matching feature or throw an IllegalArgumentException if no
	 *         feature matches
	 */
	public static DescriptionType fromString(final String string) {
		return lookup(string);
	}

	public boolean hasSearchCategory() {
		return getSearchCategory() != null;
	}

	public String getSearchCategory() {
		for(String category : searchCategories.keySet()) {
			if(searchCategories.get(category).contains(this)) {
				return category;
			}
		}

		return null;
	}

	public static List<DescriptionType> getSubTypes(final DescriptionType type){
		List<DescriptionType> types = new ArrayList<DescriptionType>();
		for(DescriptionType description : DescriptionType.values()){
			if(description.name().startsWith(type.name())){
				types.add(description);
			}
		}
		return types;
	}
	
	private static DescriptionType lookup(final String string) {
		for (DescriptionType f : DescriptionType.values()) {
			if ((f.uri != null && f.uri.equals(string)) || (f.term != null && f.term.equals(string))) {
				return f;
			}
		}
		throw new IllegalArgumentException(string
				+ " is not an acceptable value for DescriptionType");
	}
}