#===========================================================================
# allowed DPIs
#===========================================================================
dpis: [300, 190, 127, 56]

#===========================================================================
# allowed Formats
#===========================================================================
formats: ['*']

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 25000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 4000000
  - 8000000
  - 20000000
  - 40000000
  - 80000000
  - 120000000
  - 160000000

outputFilename: 'map-${date}.pdf'

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
  - !dnsMatch
    host: e-monocot.org
    port: 80

layouts:
  #===========================================================================
  A4 portrait:
  #===========================================================================
    metaData:
      title: '${title}'
      author: 'eMonocot Map Printer'
      subject: 'Simple layout'
      keywords: 'map,print'
      creator: 'MapFish'

    #-------------------------------------------------------------------------
    mainPage:
      pageSize: A4
      rotation: true

      items:
        - !map	 	
          width:  595 	
          height: 595
