insert into Source (id, identifier, uri) values (10, 'test', 'http://example.com');
insert into Reference (id, identifier,title) values (1, 'urn:kew.org:wcs:placeOfPublication:899','Bull. Pacific Orchid Soc. Hawaii');
insert into Taxon (id, identifier, name, family) values (1, 'urn:lsid:cate-araceae.org:taxon:5cd5a6aa-6bfb-1014-a918-dc439151c9e5', 'Acontias conspurcatus','test');
insert into Taxon (id, identifier, name, family) values (2, 'urn:lsid:cate-araceae.org:taxon:5cd5c756-6bfb-1014-a918-dc439151c9e5', 'Acontias cubensis','test');
insert into Taxon (id, identifier, name, family) values (3, 'urn:lsid:cate-araceae.org:taxon:5cd5e85c-6bfb-1014-a918-dc439151c9e5', 'Acontias diversifolius','test');
insert into Taxon (id, identifier, name, family) values (4, 'urn:lsid:cate-araceae.org:taxon:5c7a00ea-6bfb-1014-a918-dc439151c9e5', 'Acontias hastifolius','test');
insert into Taxon (id, identifier, name, family) values (5, 'urn:lsid:cate-araceae.org:taxon:5cd6156a-6bfb-1014-a918-dc439151c9e5', 'Acontias helleborifolius','test');
insert into Taxon (id, identifier, name, family) values (6, 'urn:lsid:cate-araceae.org:taxon:5c7a04f7-6bfb-1014-a918-dc439151c9e5', 'Acontias hoffmannii','test');
insert into Taxon (id, identifier, name, family) values (7, 'urn:lsid:cate-araceae.org:taxon:5c7a08f9-6bfb-1014-a918-dc439151c9e5', 'Acontias luridus','test');
insert into Taxon (id, identifier, name, family) values (8, 'urn:lsid:cate-araceae.org:taxon:5c7478df-6bfb-1014-a918-dc439151c9e5', 'Acontias platylobus','test');
insert into Taxon (id, identifier, name, family) values (9, 'urn:lsid:cate-araceae.org:taxon:5c7a0cef-6bfb-1014-a918-dc439151c9e5', 'Acontias plumieri','test');
insert into Taxon (id, identifier, name, family) values (10, 'urn:lsid:cate-araceae.org:taxon:5c747dbe-6bfb-1014-a918-dc439151c9e5', 'Acontias riedelianus','test');
insert into Taxon (id, identifier, name, family) values (11, 'urn:lsid:cate-araceae.org:taxon:5cd66483-6bfb-1014-a918-dc439151c9e5', 'Acontias striatipes','test');
insert into Taxon (id, identifier, name, family) values (12, 'urn:lsid:cate-araceae.org:taxon:5cd6850d-6bfb-1014-a918-dc439151c9e5', 'Acontias variegatus','test');
insert into Taxon (id, identifier, name, family) values (13, 'urn:lsid:cate-araceae.org:taxon:5c74820b-6bfb-1014-a918-dc439151c9e5', 'Acontias wendlandii','test');
insert into Taxon (id, identifier, name, family) values (14, 'urn:lsid:cate-araceae.org:taxon:5cd58503-6bfb-1014-a918-dc439151c9e5', 'Acontias','test');
insert into Taxon (id, identifier, name, family) values (15, 'urn:lsid:cate-araceae.org:taxon:5cd6c8e9-6bfb-1014-a918-dc439151c9e5', 'Adelonema erythropus','test');
insert into Taxon (id, identifier, name, family) values (16, 'urn:lsid:cate-araceae.org:taxon:5cd6a8b2-6bfb-1014-a918-dc439151c9e5', 'Adelonema','test');
insert into Taxon (id, identifier, name, family) values (17, 'urn:lsid:cate-project.org:taxon:19c6f4d2-3336-46bc-bba3-a4880cf62196', 'Afrorhaphidophora africana','test');
insert into Taxon (id, identifier, name, family) values (18, 'urn:lsid:grassbase.kew.org:taxa:387039', 'Elyhordeum × montanense','test');
insert into Taxon (id, identifier, name, family) values (19, 'urn:kew.org:wcs:taxon:303017', 'Conanthera johowi','Tecophilaeaceae');
insert into Taxon (id, accepted_id, identifier, name, family) values (20, 18, 'urn:lsid:grassbase.kew.org:taxa:387038', '× Elyhordeum macounii','test');
insert into Taxon (id, accepted_id, identifier, name, family) values (21, 18, 'urn:lsid:grassbase.kew.org:taxa:387040', '× Elyhordeum pavlovii','test');
insert into Taxon (id, identifier, name) values (22, 'urn:kew.org:wcs:family:32', 'Orchidaceae');
insert into Taxon (id, identifier, name, family,parent_id, protologue_id) values (23, 'urn:kew.org:wcs:taxon:70052', '× Epilaeliopsis auct.','Orchidaceae',22,1);
insert into Taxon (id, identifier, name, family, parent_id) values (24, 'urn:kew.org:wcs:taxon:70053', NULL,'Orchidaceae',23);
insert into Taxon (id, identifier, name, family, parent_id) values (25, 'urn:kew.org:wcs:taxon:67664', 'Epidendrum','Orchidaceae',22);
insert into Taxon (id, identifier, name, family, parent_id) values (26, 'urn:kew.org:wcs:taxon:68574', 'Epidendrum hemiscleria','Orchidaceae',25);
insert into Taxon (id, identifier, name, family,parent_id) values (27, 'urn:kew.org:wcs:taxon:71680', NULL, NULL, NULL);
insert into Taxon (id, identifier, name, family,parent_id) values (29, 'urn:kew.org:wcs:taxon:345361', 'Eriochilus dilatatus subsp. dilatatus','Orchidaceae',27);
insert into Taxon (id, identifier, name, family,parent_id) values (30, 'urn:kew.org:wcs:taxon:71685', NULL, NULL, NULL);
insert into Taxon (id, identifier, name, family,parent_id) values (31, 'urn:kew.org:wcs:taxon:345362', 'Eriochilus scaber subsp. scaber','Orchidaceae',30);
insert into Taxon (id, identifier, name, family,parent_id) values (32, 'urn:kew.org:wcs:taxon:346829', NULL, NULL, NULL);
insert into Taxon (id, identifier, name, family,parent_id) values (33, 'urn:kew.org:wcs:taxon:345506', 'Erasanthe henrici var. henrici','Orchidaceae',32);
insert into Taxon (id, identifier, name, family,parent_id) values (34, 'urn:kew.org:wcs:taxon:67580', NULL, NULL, 22);
insert into Taxon (id, identifier, name, family,parent_id) values (35, 'urn:kew.org:wcs:taxon:67588', 'Epiblastus cuneatus', 'Orchidaceae', 34);
insert into Taxon (id, identifier, name, family,parent_id) values (36, 'urn:kew.org:wcs:taxon:67589', 'Epiblastus cuneatus var. cuneatus', 'Orchidaceae', 35);
insert into Taxon (id, identifier, name) values (37, 'urn:kew.org:wcs:taxon:100446','Howea Becc.');
insert into Taxon (id, identifier, name) values (38, 'urn:kew.org:wcs:taxon:100447','Howea belmoreana (C.Moore & F.Muell.) Becc.');
insert into Taxon (id, identifier, name) values (39, 'urn:kew.org:wcs:taxon:100448','Howea forsteriana (F.Muell.) Becc.');
insert into Taxon (id, identifier, name) values (40, 'urn:kew.org:wcs:taxon:101020','Hydriastele affinis (Becc.) W.J.Baker & Loo');
insert into Taxon (id, identifier, name) values (41, 'urn:kew.org:wcs:taxon:37679','Chamaedorea verecunda Grayum & Hodel');
insert into Taxon (id, identifier, name) values (42, 'urn:kew.org:wcs:taxon:37674','Chamaedorea undulatifolia Hodel & N.W.Uhl');
insert into Taxon (id, identifier, name) values (43, 'urn:kew.org:wcs:taxon:170755','Ptychococcus Becc.');
insert into Distribution (id, region, taxon_id) values (1,'DOM',23);
