#!/bin/bash
clear

rm -rf sandbox
mkdir sandbox
cd sandbox/
export CVSROOT=$3@cvs:/var/cvs
export ANT_OPTS=-Xmx512m
cvs checkout -r $1 emonocot
cd emonocot/emonocot-portal
ant -Dprofile=$2 update-database
ant -Dprofile=$2 redeploy 
ant -Dprofile=$2 upload
echo "redeployed emonocot-portal to $2 successfully"
